export const data1 = [
    {
        name: "1PM",
        Temperature: 55,
        Ph:12 ,
        Dissolved_oxygen: 30,
        Turbidity: 39,
      },
      {
        name: "2PM",
        Temperature: 62,
        Ph: 7,
        Dissolved_oxygen: 124,
        Turbidity: 25,
      },
      {
        name: "3PM",
        Temperature: 24,
        Ph: 5,
        Dissolved_oxygen: 60,
        Turbidity: 89,
      },
      {
        name: "4PM",
        Temperature: 46,
        Ph: 1,
        Dissolved_oxygen: 171,
        Turbidity: 59,
      },
      {
        name: "5PM",
        Temperature: 80,
        Ph: 14,
        Dissolved_oxygen: 478,
        Turbidity: 37,
      },
      {
        name: "6PM",
        Temperature: 10,
        Ph: 2,
        Dissolved_oxygen: 312,
        Turbidity: 48,
      },
      {
        name: "7PM",
        Temperature: 62,
        Ph: 12,
        Dissolved_oxygen: 312,
        Turbidity: 70,
      },
]